sudo : required

language : generic

branches:
  only:
    - master

services:
  -docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test --

deploy :
  provider : elasticbeanstalk
  region : "us-east-1"
  app : "docker-react-app"
  env : "Dockerreactapp-env"
  bucket_name : "elasticbeanstalk-us-east-1-162863752933"
  bucket_path : "docker-react-app"
  on : 
    branch : master

  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : 
    secure: $AWS_SECRET_ACCESS_KEY